[build]
command = "npm install --include=dev && ./node_modules/.bin/ng build"
publish = "dist/comparehub"

[build.environment]
NODE_VERSION = "18"
NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200